# vim:fileencoding=utf-8:foldmethod=marker

# : Manager {{{

[mgr]
cwd = { fg = "#d8a657" }

# Find
find_keyword = { fg = "#a9b665", bold = true, italic = true, underline = true }
find_position = { fg = "#e78a4e", bg = "reset", bold = true, italic = true }

# Marker
marker_copied = { fg = "#89b482", bg = "#89b482" }
marker_cut = { fg = "#d3869b", bg = "#d3869b" }
marker_marked = { fg = "#7daea3", bg = "#7daea3" }
marker_selected = { fg = "#d8a657", bg = "#d8a657" }

# Count
count_copied = { fg = "#1c1e21", bg = "#89b482" }
count_cut = { fg = "#1c1e21", bg = "#d3869b" }
count_selected = { fg = "#1c1e21", bg = "#d4be98" }

# Border
border_symbol = "│"
border_style = { fg = "#d4be98" }

# : }}}


# : Tabs {{{

[tabs]
active = { fg = "#1c1e21", bg = "#d4be98" }
inactive = { fg = "#d4be98", bg = "#3c3836" }

# : }}}


# : Mode {{{

[mode]
normal_main = { fg = "#1c1e21", bg = "#d4be98", bold = true }
normal_alt = { fg = "#d4be98", bg = "#3c3836" }

# Select mode
select_main = { fg = "#1c1e21", bg = "#89b482", bold = true }
select_alt = { fg = "#89b482", bg = "#3c3836" }

# Unset mode
unset_main = { fg = "#1c1e21", bg = "#d3869b", bold = true }
unset_alt = { fg = "#d3869b", bg = "#3c3836" }

# : }}}


# : Status bar {{{

[status]
# Permissions
perm_sep = { fg = "#665c54" }
perm_type = { fg = "#7daea3" }
perm_read = { fg = "#ddc7a1" }
perm_write = { fg = "#ea6962" }
perm_exec = { fg = "#a9b665" }

# Progress
progress_label = { fg = "#ddc7a1", bold = true }
progress_normal = { fg = "#3c3836", bg = "#32302f" }
progress_error = { fg = "#ea6962", bg = "#32302f" }

# : }}}


# : Picker {{{

[pick]
border = { fg = "#7daea3" }
active = { fg = "#d3869b", bold = true }
inactive = {}

# : }}}


# : Input {{{

[input]
border = { fg = "#d4be98" }
title = {}
value = {}
selected = { reversed = true }

# : }}}


# : Completion {{{

[cmp]
border = { fg = "#d4be98" }

# : }}}


# : Tasks {{{

[tasks]
border = { fg = "#3c3836" }
title = {}
hovered = { fg = "#d3869b", bold = true }

# : }}}


# : Which {{{

[which]
mask = { bg = "#3c3836" }
cand = { fg = "#89b482" }
rest = { fg = "#a89984" }
desc = { fg = "#d4be98" }
separator = "  "
separator_style = { fg = "#504945" }

# : }}}


# : Help {{{
[help]
on = { fg = "#89b482" }
run = { fg = "#d3869b" }
hovered = { reversed = true, bold = true }
footer = { fg = "#3c3836", bg = "#d4be98" }

# : }}}


# : Spotter {{{

[spot]
border = { fg = "#7daea3" }
title = { fg = "#7daea3" }
tbl_col = { fg = "#89b482" }
tbl_cell = { fg = "#d3869b", bg = "#504945" }

# : }}}


# : Notification {{{

[notify]
title_info = { fg = "#a9b665" }
title_warn = { fg = "#d8a657" }
title_error = { fg = "#ea6962" }

# : }}}


# : File-specific styles {{{

[filetype]

rules = [
  # Images
  { mime = "image/*", fg = "#d3869b" },
  # Media
  { mime = "{audio,video}/*", fg = "#d8a657" },
  # Archives
  { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#ea6962" },
  # Documents
  { mime = "application/{pdf,doc,rtf,vnd.*}", fg = "#89b482" },
  # Fallback
  { url = "*", fg = "#ddc7a1" },
  { url = "*/", fg = "#7daea3" },
  { name = "*", fg = "#ddc7a1" },
  { name = "*/", fg = "#7daea3" },
]

# : }}}


# : Icons {{{

[icon]
prepend_conds = [
  { if = "dir", text = "" },
  { if = "!(dir | link)", text = "" }, # Normal files (not directories or symlinks)
]

# : }}}
